import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { compare } from 'bcryptjs'
import { getSessionUser } from '@/lib/session'
import { requireAuth } from '@/lib/auth-helpers'
import { prisma } from '@/lib/prisma'
import { generateTotpSecret, getTotpUri, encryptTotpSecret, decryptTotpSecret, verifyTotpCode } from '@/lib/auth/totp'
import { checkRateLimit, RATE_LIMITS } from '@/lib/rate-limit'
import QRCode from 'qrcode'

const bodySchema = z
  .object({
    password: z.string().min(1).optional(),
    code: z.string().min(1).optional(),
  })
  .optional()

// POST /api/auth/2fa/setup
// Generates a TOTP secret, stores it (encrypted, not yet enabled), returns QR code.
// requireAuth() enforces a full (non-pending2fa) session AND re-checks tokenVersion
// revocation and account status server-side — raw auth() skipped both.
//
// Re-enrolment is a credential change, not a convenience: once 2FA is enabled the
// caller must prove possession again (current TOTP code, or the account password)
// before the stored secret is replaced. Without that, a stolen session could swap
// in the attacker's authenticator, and an accidental second setup would silently
// brick the legitimate one.
export async function POST(req: NextRequest) {
  // exempt: an unenrolled admin must be able to reach setup to enrol at all.
  const { session, response } = await requireAuth({ exemptAdminTwoFactorSetup: true })
  if (!session) return response!

  const sessionUser = getSessionUser(session)
  const userId = sessionUser.id
  const email = (sessionUser.email as string) ?? ''

  const me = await prisma.user.findUnique({
    where: { id: userId },
    select: { twoFactorEnabled: true, twoFactorSecret: true, passwordHash: true },
  })
  if (!me) return NextResponse.json({ error: 'Account no longer exists' }, { status: 401 })

  if (me.twoFactorEnabled) {
    // Same limiter as the login challenge — this path also accepts a 6-digit code.
    const { allowed } = await checkRateLimit(RATE_LIMITS.twoFactor, userId, { failMode: 'closed' })
    if (!allowed) {
      return NextResponse.json(
        { error: 'Too many attempts. Please wait a few minutes and try again.' },
        { status: 429 },
      )
    }

    const parsed = bodySchema.safeParse(await req.json().catch(() => undefined))
    if (!parsed.success) {
      return NextResponse.json({ error: 'Invalid request.' }, { status: 400 })
    }
    const { password, code } = parsed.data ?? {}

    let reauthenticated = false
    if (code && me.twoFactorSecret) {
      try {
        reauthenticated = verifyTotpCode(decryptTotpSecret(me.twoFactorSecret), code)
      } catch {
        reauthenticated = false
      }
    }
    if (!reauthenticated && password && me.passwordHash) {
      reauthenticated = await compare(password, me.passwordHash)
    }

    if (!reauthenticated) {
      return NextResponse.json(
        {
          error:
            'Two-factor authentication is already on for this account. Enter your current authenticator code or your password to set up a new device.',
          code: 'REAUTH_REQUIRED',
        },
        { status: 403 },
      )
    }
  }

  const secret = generateTotpSecret()
  const encrypted = encryptTotpSecret(secret)

  // Park the new secret in the pending slot. The active secret — and therefore the
  // authenticator the user is holding right now — stays untouched until /2fa/enable
  // verifies a code generated by the new device.
  await prisma.user.update({
    where: { id: userId },
    data: { twoFactorPendingSecret: encrypted },
  })

  const uri = getTotpUri(secret, email)
  const qrDataUrl = await QRCode.toDataURL(uri)

  return NextResponse.json({ qrDataUrl, secret, uri })
}
