export type FieldAdmissibility = 'compulsory' | 'conditional' | 'optional'

export interface FieldDefinition {
  name: string
  admissibility: FieldAdmissibility
  condition?: string
  conditionFn?: (fields: Record<string, string | null>) => boolean
}

export const DOCUMENT_FIELD_DEFINITIONS: Record<string, FieldDefinition[]> = {
  ELECTRICITY_BILL: [
    { name: 'account_holder_name', admissibility: 'compulsory' },
    { name: 'site_address', admissibility: 'compulsory' },
    { name: 'meter_reference', admissibility: 'compulsory' },
    { name: 'period_start', admissibility: 'compulsory' },
    { name: 'period_end', admissibility: 'compulsory' },
    { name: 'total_consumption_kwh', admissibility: 'compulsory' },
    { name: 'read_type', admissibility: 'compulsory' },
    { name: 'supplier_name', admissibility: 'compulsory' },
    { name: 'invoice_number', admissibility: 'compulsory' },
    { name: 'invoice_date', admissibility: 'compulsory' },
    { name: 'tariff_name', admissibility: 'optional' },
    { name: 'unit_rate_p_per_kwh', admissibility: 'optional' },
    { name: 'standing_charge', admissibility: 'optional' },
    { name: 'vat_number', admissibility: 'optional' },
  ],

  GAS_BILL: [
    { name: 'account_holder_name', admissibility: 'compulsory' },
    { name: 'site_address', admissibility: 'compulsory' },
    { name: 'meter_reference', admissibility: 'compulsory' },
    { name: 'period_start', admissibility: 'compulsory' },
    { name: 'period_end', admissibility: 'compulsory' },
    { name: 'total_consumption_kwh', admissibility: 'compulsory' },
    { name: 'read_type', admissibility: 'compulsory' },
    { name: 'supplier_name', admissibility: 'compulsory' },
    { name: 'invoice_number', admissibility: 'compulsory' },
    { name: 'invoice_date', admissibility: 'compulsory' },
    {
      name: 'total_consumption_m3',
      admissibility: 'conditional',
      condition: 'kWh figure is derived from m³',
      conditionFn: (f) => f['calorific_value'] !== null,
    },
    {
      name: 'calorific_value',
      admissibility: 'conditional',
      condition: 'm³ to kWh conversion present in document',
      conditionFn: (f) => f['total_consumption_m3'] !== null,
    },
    {
      name: 'calorific_value_unit',
      admissibility: 'conditional',
      condition: 'calorific_value is present',
      conditionFn: (f) => f['calorific_value'] !== null,
    },
  ],

  FUEL_RECEIPT: [
    { name: 'purchaser_name', admissibility: 'compulsory' },
    { name: 'fuel_type', admissibility: 'compulsory' },
    { name: 'quantity', admissibility: 'compulsory' },
    { name: 'unit', admissibility: 'compulsory' },
    { name: 'purchase_date', admissibility: 'compulsory' },
    { name: 'supplier_name', admissibility: 'compulsory' },
    { name: 'receipt_or_invoice_number', admissibility: 'compulsory' },
    { name: 'use_type', admissibility: 'compulsory' },
    {
      name: 'site_or_vehicle_reference',
      admissibility: 'conditional',
      condition: 'use_type is STATIONARY_COMBUSTION or TRANSPORT',
      conditionFn: (f) =>
        f['use_type'] === 'STATIONARY_COMBUSTION' || f['use_type'] === 'TRANSPORT',
    },
  ],

  RENEWABLE_CERTIFICATE: [
    { name: 'certificate_type', admissibility: 'compulsory' },
    { name: 'issuing_body', admissibility: 'compulsory' },
    { name: 'certificate_number', admissibility: 'compulsory' },
    { name: 'holder_name', admissibility: 'compulsory' },
    { name: 'vintage_year', admissibility: 'compulsory' },
    { name: 'quantity_mwh', admissibility: 'compulsory' },
    { name: 'technology_type', admissibility: 'compulsory' },
    { name: 'generation_country', admissibility: 'compulsory' },
    { name: 'expiry_date', admissibility: 'compulsory' },
  ],

  PRODUCTION_LOG: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'site_name', admissibility: 'compulsory' },
    { name: 'product_type', admissibility: 'compulsory' },
    { name: 'product_specification', admissibility: 'compulsory' },
    { name: 'quantity_produced', admissibility: 'compulsory' },
    { name: 'unit', admissibility: 'compulsory' },
    { name: 'period_start', admissibility: 'compulsory' },
    { name: 'period_end', admissibility: 'compulsory' },
    { name: 'process_stage', admissibility: 'compulsory' },
    { name: 'log_or_batch_reference', admissibility: 'compulsory' },
    { name: 'energy_consumption_total', admissibility: 'optional' },
    {
      name: 'energy_unit',
      admissibility: 'conditional',
      condition: 'energy_consumption_total is present',
      conditionFn: (f) => f['energy_consumption_total'] !== null,
    },
  ],

  MATERIAL_INTAKE: [
    { name: 'receiving_entity', admissibility: 'compulsory' },
    { name: 'receiving_site', admissibility: 'compulsory' },
    { name: 'supplier_name', admissibility: 'compulsory' },
    { name: 'material_type', admissibility: 'compulsory' },
    { name: 'material_specification', admissibility: 'compulsory' },
    { name: 'quantity', admissibility: 'compulsory' },
    { name: 'unit', admissibility: 'compulsory' },
    { name: 'delivery_date', admissibility: 'compulsory' },
    { name: 'delivery_note_reference', admissibility: 'compulsory' },
    { name: 'purchase_order_reference', admissibility: 'conditional', condition: 'entity uses PO process' },
    { name: 'country_of_origin', admissibility: 'optional' },
    { name: 'supplier_invoice_reference', admissibility: 'optional' },
  ],

  BILL_OF_MATERIALS: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'product_type', admissibility: 'compulsory' },
    { name: 'product_specification', admissibility: 'compulsory' },
    { name: 'bom_version', admissibility: 'compulsory' },
    { name: 'effective_date', admissibility: 'compulsory' },
    { name: 'line_items', admissibility: 'compulsory' },
    { name: 'total_mass_per_unit', admissibility: 'optional' },
    {
      name: 'total_mass_unit',
      admissibility: 'conditional',
      condition: 'total_mass_per_unit is present',
      conditionFn: (f) => f['total_mass_per_unit'] !== null,
    },
  ],

  PROCESS_DATA_SHEET: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'site_name', admissibility: 'compulsory' },
    { name: 'process_type', admissibility: 'compulsory' },
    { name: 'period_start', admissibility: 'compulsory' },
    { name: 'period_end', admissibility: 'compulsory' },
    { name: 'inputs', admissibility: 'compulsory' },
    { name: 'outputs', admissibility: 'compulsory' },
    { name: 'energy_consumption', admissibility: 'optional' },
    {
      name: 'energy_unit',
      admissibility: 'conditional',
      condition: 'energy_consumption is present',
      conditionFn: (f) => f['energy_consumption'] !== null,
    },
    {
      name: 'emission_factors_cited',
      admissibility: 'conditional',
      condition: 'document contains calculated emissions figures',
    },
  ],

  FREIGHT_INVOICE: [
    { name: 'carrier_name', admissibility: 'compulsory' },
    { name: 'shipper_name', admissibility: 'compulsory' },
    { name: 'consignee_name', admissibility: 'compulsory' },
    { name: 'origin_city', admissibility: 'compulsory' },
    { name: 'origin_country', admissibility: 'compulsory' },
    { name: 'destination_city', admissibility: 'compulsory' },
    { name: 'destination_country', admissibility: 'compulsory' },
    { name: 'mode_of_transport', admissibility: 'compulsory' },
    { name: 'shipment_weight', admissibility: 'compulsory' },
    { name: 'weight_unit', admissibility: 'compulsory' },
    { name: 'shipment_date', admissibility: 'compulsory' },
    { name: 'invoice_number', admissibility: 'compulsory' },
    { name: 'invoice_date', admissibility: 'compulsory' },
    {
      name: 'multimodal_leg_breakdown',
      admissibility: 'conditional',
      condition: 'mode_of_transport is MULTIMODAL',
      conditionFn: (f) => f['mode_of_transport'] === 'MULTIMODAL',
    },
    { name: 'distance_km', admissibility: 'optional' },
    { name: 'container_reference', admissibility: 'optional' },
  ],

  DELIVERY_NOTE: [
    { name: 'shipper_name', admissibility: 'compulsory' },
    { name: 'consignee_name', admissibility: 'compulsory' },
    { name: 'delivery_date', admissibility: 'compulsory' },
    { name: 'delivery_note_reference', admissibility: 'compulsory' },
    { name: 'line_items', admissibility: 'compulsory' },
    { name: 'purchase_order_reference', admissibility: 'optional' },
    { name: 'freight_invoice_reference', admissibility: 'optional' },
  ],

  CUSTOMS_DECLARATION: [
    { name: 'importer_name', admissibility: 'compulsory' },
    { name: 'commodity_code', admissibility: 'compulsory' },
    { name: 'commodity_description', admissibility: 'compulsory' },
    { name: 'country_of_origin', admissibility: 'compulsory' },
    { name: 'country_of_dispatch', admissibility: 'compulsory' },
    { name: 'declared_weight', admissibility: 'compulsory' },
    { name: 'weight_unit', admissibility: 'compulsory' },
    { name: 'declaration_reference', admissibility: 'compulsory' },
    { name: 'declaration_date', admissibility: 'compulsory' },
    { name: 'customs_procedure', admissibility: 'optional' },
    { name: 'declared_value', admissibility: 'optional' },
    {
      name: 'currency',
      admissibility: 'conditional',
      condition: 'declared_value is present',
      conditionFn: (f) => f['declared_value'] !== null,
    },
  ],

  BILL_OF_LADING: [
    { name: 'shipper_name', admissibility: 'compulsory' },
    { name: 'consignee_name', admissibility: 'compulsory' },
    { name: 'port_of_loading', admissibility: 'compulsory' },
    { name: 'port_of_discharge', admissibility: 'compulsory' },
    { name: 'commodity_description', admissibility: 'compulsory' },
    { name: 'gross_weight', admissibility: 'compulsory' },
    { name: 'gross_weight_unit', admissibility: 'compulsory' },
    { name: 'bill_of_lading_number', admissibility: 'compulsory' },
    { name: 'date_of_issue', admissibility: 'compulsory' },
    { name: 'vessel_name', admissibility: 'optional' },
    { name: 'container_numbers', admissibility: 'optional' },
  ],

  SUPPLIER_INVOICE: [
    { name: 'supplier_name', admissibility: 'compulsory' },
    { name: 'buyer_name', admissibility: 'compulsory' },
    { name: 'invoice_number', admissibility: 'compulsory' },
    { name: 'invoice_date', admissibility: 'compulsory' },
    { name: 'line_items', admissibility: 'compulsory' },
    { name: 'currency', admissibility: 'compulsory' },
    { name: 'total_value', admissibility: 'compulsory' },
    { name: 'supplier_registration_number', admissibility: 'optional' },
    { name: 'purchase_order_reference', admissibility: 'optional' },
  ],

  PURCHASE_ORDER: [
    { name: 'buyer_name', admissibility: 'compulsory' },
    { name: 'supplier_name', admissibility: 'compulsory' },
    { name: 'po_number', admissibility: 'compulsory' },
    { name: 'po_date', admissibility: 'compulsory' },
    { name: 'line_items', admissibility: 'compulsory' },
    { name: 'currency', admissibility: 'compulsory' },
    { name: 'delivery_due_date', admissibility: 'optional' },
  ],

  SUPPLIER_QUESTIONNAIRE: [
    { name: 'supplier_name', admissibility: 'compulsory' },
    { name: 'responding_entity', admissibility: 'compulsory' },
    { name: 'reporting_period_start', admissibility: 'compulsory' },
    { name: 'reporting_period_end', admissibility: 'compulsory' },
    { name: 'response_completeness', admissibility: 'compulsory' },
    { name: 'methodology_stated', admissibility: 'compulsory' },
  ],

  ENVIRONMENTAL_CERTIFICATE: [
    { name: 'certificate_holder_name', admissibility: 'compulsory' },
    { name: 'standard', admissibility: 'compulsory' },
    { name: 'issuing_body', admissibility: 'compulsory' },
    { name: 'accreditation_body', admissibility: 'compulsory' },
    { name: 'certificate_number', admissibility: 'compulsory' },
    { name: 'scope', admissibility: 'compulsory' },
    { name: 'issue_date', admissibility: 'compulsory' },
    { name: 'expiry_date', admissibility: 'compulsory' },
  ],

  CBAM_DECLARATION: [
    { name: 'declarant_name', admissibility: 'compulsory' },
    { name: 'commodity_code', admissibility: 'compulsory' },
    { name: 'commodity_description', admissibility: 'compulsory' },
    { name: 'country_of_origin', admissibility: 'compulsory' },
    { name: 'production_period_start', admissibility: 'compulsory' },
    { name: 'production_period_end', admissibility: 'compulsory' },
    { name: 'quantity_tonnes', admissibility: 'compulsory' },
    { name: 'embedded_emissions_tco2e', admissibility: 'compulsory' },
    { name: 'embedded_emissions_per_tonne', admissibility: 'compulsory' },
    { name: 'calculation_tier', admissibility: 'compulsory' },
    { name: 'calculation_methodology', admissibility: 'compulsory' },
    {
      name: 'supporting_data_reference',
      admissibility: 'conditional',
      condition: 'calculation_tier is TIER_1 or TIER_2',
      conditionFn: (f) =>
        f['calculation_tier'] === 'TIER_1' || f['calculation_tier'] === 'TIER_2',
    },
  ],

  WASTE_RECORD: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'site_name', admissibility: 'compulsory' },
    { name: 'waste_type', admissibility: 'compulsory' },
    { name: 'waste_classification', admissibility: 'compulsory' },
    { name: 'quantity', admissibility: 'compulsory' },
    { name: 'unit', admissibility: 'compulsory' },
    { name: 'disposal_method', admissibility: 'compulsory' },
    { name: 'contractor_name', admissibility: 'compulsory' },
    { name: 'contractor_licence', admissibility: 'compulsory' },
    { name: 'period_start', admissibility: 'compulsory' },
    { name: 'period_end', admissibility: 'compulsory' },
    { name: 'record_reference', admissibility: 'compulsory' },
  ],

  WATER_RECORD: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'site_name', admissibility: 'compulsory' },
    { name: 'water_source_type', admissibility: 'compulsory' },
    { name: 'quantity_m3', admissibility: 'compulsory' },
    { name: 'period_start', admissibility: 'compulsory' },
    { name: 'period_end', admissibility: 'compulsory' },
    { name: 'meter_reference', admissibility: 'optional' },
    { name: 'record_reference', admissibility: 'optional' },
  ],

  CROP_YIELD_RECORD: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'site_or_field_id', admissibility: 'compulsory' },
    { name: 'crop_type', admissibility: 'compulsory' },
    { name: 'crop_variety', admissibility: 'optional' },
    { name: 'area_hectares', admissibility: 'compulsory' },
    { name: 'yield_quantity', admissibility: 'compulsory' },
    { name: 'yield_unit', admissibility: 'compulsory' },
    { name: 'harvest_date', admissibility: 'compulsory' },
    { name: 'season', admissibility: 'optional' },
    { name: 'certification_reference', admissibility: 'optional' },
  ],

  FERTILISER_RECORD: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'site_or_field_id', admissibility: 'compulsory' },
    { name: 'product_name', admissibility: 'compulsory' },
    { name: 'nitrogen_content_percent', admissibility: 'compulsory' },
    {
      name: 'phosphorus_content_percent',
      admissibility: 'conditional',
      condition: 'product is an NPK fertiliser',
      conditionFn: (f) => (f['product_name'] ?? '').toLowerCase().includes('npk'),
    },
    {
      name: 'potassium_content_percent',
      admissibility: 'conditional',
      condition: 'product is an NPK fertiliser',
      conditionFn: (f) => (f['product_name'] ?? '').toLowerCase().includes('npk'),
    },
    { name: 'quantity_applied_per_hectare', admissibility: 'compulsory' },
    { name: 'application_rate_unit', admissibility: 'compulsory' },
    { name: 'total_quantity_applied', admissibility: 'compulsory' },
    { name: 'total_unit', admissibility: 'compulsory' },
    { name: 'application_date', admissibility: 'compulsory' },
    { name: 'application_method', admissibility: 'optional' },
  ],

  LIVESTOCK_RECORD: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'site_name', admissibility: 'compulsory' },
    { name: 'species', admissibility: 'compulsory' },
    { name: 'breed', admissibility: 'optional' },
    { name: 'average_herd_size', admissibility: 'compulsory' },
    { name: 'period_start', admissibility: 'compulsory' },
    { name: 'period_end', admissibility: 'compulsory' },
    { name: 'feed_type', admissibility: 'optional' },
    { name: 'feed_quantity', admissibility: 'optional' },
    {
      name: 'feed_unit',
      admissibility: 'conditional',
      condition: 'feed_quantity is present',
      conditionFn: (f) => f['feed_quantity'] !== null,
    },
    { name: 'record_reference', admissibility: 'optional' },
  ],

  LAND_USE_CERTIFICATE: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'land_parcel_reference', admissibility: 'compulsory' },
    { name: 'land_use_type', admissibility: 'compulsory' },
    { name: 'area_hectares', admissibility: 'compulsory' },
    { name: 'issuing_body', admissibility: 'compulsory' },
    { name: 'certificate_number', admissibility: 'compulsory' },
    { name: 'issue_date', admissibility: 'compulsory' },
    { name: 'expiry_date', admissibility: 'compulsory' },
    { name: 'geographic_coordinates', admissibility: 'optional' },
    { name: 'certification_standard', admissibility: 'optional' },
  ],

  PRODUCT_CERTIFICATE: [
    { name: 'certificate_holder_name', admissibility: 'compulsory' },
    { name: 'certificate_type', admissibility: 'compulsory' },
    { name: 'issuing_body', admissibility: 'compulsory' },
    { name: 'certificate_number', admissibility: 'compulsory' },
    { name: 'scope_of_certification', admissibility: 'compulsory' },
    { name: 'issue_date', admissibility: 'compulsory' },
    { name: 'expiry_date', admissibility: 'compulsory' },
    { name: 'audit_or_verification_date', admissibility: 'optional' },
  ],

  CHAIN_OF_CUSTODY: [
    { name: 'document_reference', admissibility: 'compulsory' },
    { name: 'product_type', admissibility: 'compulsory' },
    { name: 'custody_stages', admissibility: 'compulsory' },
    { name: 'origin_entity', admissibility: 'compulsory' },
    { name: 'final_entity', admissibility: 'compulsory' },
    { name: 'certification_standard', admissibility: 'compulsory' },
  ],

  CARBON_FOOTPRINT_REPORT: [
    { name: 'entity_name', admissibility: 'compulsory' },
    { name: 'report_title', admissibility: 'compulsory' },
    { name: 'methodology', admissibility: 'compulsory' },
    { name: 'system_boundary', admissibility: 'compulsory' },
    { name: 'data_year', admissibility: 'compulsory' },
    { name: 'publication_date', admissibility: 'compulsory' },
    { name: 'total_co2e', admissibility: 'compulsory' },
    { name: 'total_co2e_unit', admissibility: 'compulsory' },
    { name: 'preparer_name', admissibility: 'compulsory' },
    { name: 'assurance_level', admissibility: 'compulsory' },
    {
      name: 'assurance_body',
      admissibility: 'conditional',
      condition: 'assurance_level is not NONE',
      conditionFn: (f) => f['assurance_level'] !== null && f['assurance_level'] !== 'NONE',
    },
    { name: 'scope_1_total', admissibility: 'optional' },
    { name: 'scope_2_total', admissibility: 'optional' },
    { name: 'scope_3_total', admissibility: 'optional' },
  ],
}
